### ISSUE TITLE
npm run prod无效

### ISSUE THREAD

**Issue by sa6** [jiangxy/react-antd-mobile-demo#2]
npm run prod，编译生产环境的js，编译完成后打开dist/index-prod.html查看效果。
在window环境下，运行npm run prod报错
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序或批处理文件。
打开package.json改为
"prod": "set NODE_ENV=production webpack --progress --colors --config webpack.config.prod.js -p --display-error-details",
可以运行
蛋没有生成任何文件。怎么办

**Comment by jiangxy** [comment]
@sa6 
1. npm的安装正常的嘛？`npm install`和`npm run dev`是否正常执行？
2. clone下来时，dist目录存在么？之前有个bug。。。clone下来没有dist目录
3. `NODE_ENV`的问题，估计是在win下面设置环境变量的问题，试试把`NODE_ENV=production`去掉看能不能正常？

**Comment by sa6** [comment]
@jiangxy 厉害
1.正常
2.正常
3.NODE_ENV=production去掉后就正常执行了，生成了bundle.min.js文件。
请教：有没有完整mobile项目的demo。始终做不出好的框架来，很多问题。代码越堆越多

**Comment by jiangxy** [comment]
@sa6 
antd-mobile我也没有深入用过，因为我做的主要是一些后台类的项目
建议还是看官方文档吧：https://mobile.ant.design/
可以参考下常见的React全家桶

**Comment by sa6** [comment]
npm run prod，编译生产环境的js，编译完成后打开dist/index-prod.html查看效果。
打开之后出现警告如下，这个要怎么解决呢？
bundle.min.js:1 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

**Comment by jiangxy** [comment]
@sa6  
貌似这个是取消掉`NODE_ENV=production`的副作用
可以试试这样写`"prod": "set NODE_ENV=production&&webpack --progress --colors --config webpack.config.prod.js -p --display-error-details"`
手边没有win环境，不太好测试
